version: "3.9"

networks:
  toybooru:

services:
  # main application frontend
  service:
    image: toybooru
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    volumes:
      - ./pg_hba.conf:/etc/postgresql/pg_hba.conf
      - tbimg:/app/public/images
      - tbthumb:/app/public/thumbs
    restart: always
    ports:
      - "8000:5000"
    networks:
      - toybooru
    depends_on:
      - database
  # using postgres, because i don't want to
  # recompile sqlite
  database:
    image: postgres:16.2
    restart: always
    volumes:
      - ../postgres_setup.sql:/docker-entrypoint-initdb.d/setup.sql
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
    networks:
      - toybooru
  
  
volumes:
  pgdata:
  tbimg:
  tbthumb:
